### PR TITLE
Added Email Search Function to Reports & People Model, Fixed Bug Where Names Were Auto-Spaced When 2nd Capitalized Letter Detected in Name

### PR DESCRIPTION
**Pull request by dmliu010**
By the way, I did not test this. I couldn't get it running locally via the current instructions unfortunately.  Kept running into "We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly." error page. This code is from an old email I pulled up when I had it working locally at some point in the past. Anyways, it worked in the past (I think sometime around 2017?), so I assume it probably still works (hopefully), but proceed with caution if possible.

### CODE REVIEW

**Comment by jgravois** [comment]
I know it's not much help, but I too have been bitten by the unexpected autospacing described here.

**Comment by asalant** [comment]
Thanks @dmliu010! 

I'd love to get you set up with a working development environment so that you can verify this change, run tests, and make future changes when you have them. 

The error page you are seeing is just the standard 500 error page served by Rails. That means the Rails app is running but hitting an error trying to serve requests. 

My guess is that you're using an M1 Mac, is that correct? It looks like the mysql image specified in the docker-compose.yml file is not compatible with M1 Macs. I'm actually seeing this issue myself.

When you run `docker-compose up` do you see errors when mysql tries to start up?

I'll take a look at resolving this tomorrow.

**Comment by asalant** [comment]
Okay, fix is in master from #59.

Rebase this branch from master and see if things start up correctly for you now.

**Comment by dmliu010** [comment]
Actually, I'm on Ubuntu 20 via WSL2. I don't know if this is the problem because I don't remember running into it the 1st time when trying to set it up locally, but it seems like the Docker config is trying to find the Gemfile in the "app" directory instead of the root directory (where it's located).

**Comment by asalant** [comment]
Thanks for the detail. So the MariaDB change fixes my issue running an M1 Macbook then ;)

Rails logs its errors to `log/development.log`. When you get the error page, check the log to see what the actual error is. My guess is that the development database hasn't been created because of the error you got running `docker-compose exec app`. If I try to view `http://localhost:3000` after running `docker-compose up` but without creating the database schema, I see the following errors in the log:

```
  Status: 500 Internal Server Error
  Unknown database 'freehub_for_all_development'
    /usr/local/bundle/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `real_connect'
    /usr/local/bundle/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `connect'
    ...
```

But I don't get an error running `docker-compose exec app rake db:create`.

Let's just try start clean and run through the steps which a couple other things to try below. Run `docker-compose clean` to remove any existing images, then `docker-compose build` to rebuild the app image.

Then try `docker-compose exec app rake db:create db:schema:load db:fixtures:load` again. 

If that fails with the same error, open a shell in the app image with `docker-compose exec app bash`. This puts you in the `/app` directory of the image. This is mapped to the project root you were just in so you will see the same files. Confirm that you do. Now you can run the rake command directly with `rake db:create db:schema:load db:fixtures:load`.

What happens when you try those steps?

Also what version of docker-compose are you using? I have:

```
$ docker-compose --version
docker-compose version 1.27.4, build 40524192
```

**Comment by dmliu010** [comment]
I should be on the latest Docker version:

`docker-compose version 1.29.2, build 5becea4c`

Ah yes! That is the exact same error I am getting and the database isn't being created or it's just not able to access it for some reason. It _seems_ to be being created from the Docker output.

`  Status: 500 Internal Server Error
  Unknown database 'freehub_for_all_development'`

when I run:

`docker-compose exec app rake db:create`

I also don't get an error.

`docker-compose clean` gives me a no command found error. Do you mean  `docker-compose rm` ?

Ran the following:


`docker-compose clean`

```
Going to remove freehub_app_1, freehub_mysql_1
Are you sure? [yN] y
Removing freehub_app_1   ... done
Removing freehub_mysql_1 ... done
```

`docker-compose build`

no errors, but get:
`mysql uses an image, skipping`  _(<---- might be the problem?)_


`docker-compose exec app rake db:create db:schema:load db:fixtures:load`

_no errors_

`docker-compose up`

```

Creating freehub_mysql_1 ... done
Creating freehub_app_1   ... done
Attaching to freehub_mysql_1, freehub_app_1
...
```
Still 500 error. Checked the log file, below is the same error.

```
/!\ FAILSAFE /!\  2021-06-16 19:44:18 +0000
  Status: 500 Internal Server Error
  Unknown database 'freehub_for_all_development'
    /usr/local/bundle/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `real_connect'
    /usr/local/bundle/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `connect'

```

**Comment by asalant** [comment]
> docker-compose clean gives me a no command found error. Did you mean docker-compose rm ?

Sorry. I meant `docker-compose down`.

> mysql uses an image, skipping (<---- might be the problem?)

This is expected and what I also see.

> `docker-compose exec app rake db:create db:schema:load db:fixtures:load`
> 
> no errors

Do you get any output? I see:

```
$ docker-compose exec app rake db:create db:schema:load db:fixtures:load
DEPRECATION WARNING: Rake tasks in vendor/plugins/blue-ridge/tasks are deprecated. Use lib/tasks instead. (called from <top (required)> at /usr/local/bundle/gems/rails-2.3.17/lib/tasks/rails.rb:10)
-- create_table("notes", {:force=>true})
   -> 0.2792s
-- add_index("notes", ["created_by_id"], {:name=>"fk_notes_created_by"})
   -> 0.2206s
...
-- assume_migrated_upto_version(20100626223127, "db/migrate")
   -> 0.5561s
```


That you are getting this error tells me that Rails and MySQL (MariaDB) are starting and Rails is successfully connecting to MySQL. But that instance of MySQL doesn't have the application database set up in it:

```
Status: 500 Internal Server Error
  Unknown database 'freehub_for_all_development'
    /usr/local/bundle/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `real_connect'
    /usr/local/bundle/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `connect'
...
```

 Is it possible you already have an instance of MySQL running on port 3306 with the same authentication credentials?

**Comment by dmliu010** [comment]
> > docker-compose clean gives me a no command found error. Did you mean docker-compose rm ?
> 
> Sorry. I meant `docker-compose down`.
> 
> > mysql uses an image, skipping (<---- might be the problem?)
> 
> This is expected and what I also see.
> 
> > `docker-compose exec app rake db:create db:schema:load db:fixtures:load`
> > no errors
> 
> Do you get any output? I see:
> 
> ```
> $ docker-compose exec app rake db:create db:schema:load db:fixtures:load
> DEPRECATION WARNING: Rake tasks in vendor/plugins/blue-ridge/tasks are deprecated. Use lib/tasks instead. (called from <top (required)> at /usr/local/bundle/gems/rails-2.3.17/lib/tasks/rails.rb:10)
> -- create_table("notes", {:force=>true})
>    -> 0.2792s
> -- add_index("notes", ["created_by_id"], {:name=>"fk_notes_created_by"})
>    -> 0.2206s
> ...
> -- assume_migrated_upto_version(20100626223127, "db/migrate")
>    -> 0.5561s
> ```
> 
> That you are getting this error tells me that Rails and MySQL (MariaDB) are starting and Rails is successfully connecting to MySQL. But that instance of MySQL doesn't have the application database set up in it:
> 
> ```
> Status: 500 Internal Server Error
>   Unknown database 'freehub_for_all_development'
>     /usr/local/bundle/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `real_connect'
>     /usr/local/bundle/gems/activerecord-2.3.17/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `connect'
> ...
> ```
> 
> Is it possible you already have an instance of MySQL running on port 3306 with the same authentication credentials?

I get no output when I run `docker-compose exec app rake db:create db:schema:load db:fixtures:load`, it just jumps to the next input line.

I will try to set this up on a spare machine I have just in case it's something wrong with the machine I'm currently using.

**Comment by asalant** [comment]
Thanks for working through this with me. Getting the development environment easy to set up will be valuable for the next person who wants to contribute. And for the next change you want to make!

**Comment by dmliu010** [comment]
Alright I'm not too familiar with Docker, but when I run it on a native Ubuntu machine, get this @ step 2.
Screenshot from 2021-06-17 11-25-21

I had it working at the BK's computer (also running Ubuntu) last night except it had a problem connecting to localhost because something was being exceeded, forgot what it was, will look at it again tonight.

Maybe I should just go get my iMac from my dad's place lol.

**Comment by asalant** [comment]
Sorry. When you build the first time it doesn't create the services. `docker-compose create` should do that.

I'm not super in to the strategy of just trying on another machine. There's a reason it is not working on your original workstation. But we're not getting the logging or diagnostics we need.

Do you want to find a time to troubleshoot in real time? We can screen share on your workstation and try to sort it out.

**Comment by dmliu010** [comment]
That sounds wonderful! I am usually free any except 6-9pm Tues, Wed, Thurs, and Sat 12-3pm. All other times are fairly open.

**Comment by asalant** [comment]
Paired with @dmliu010 to resolve his Docker issues and fixed the wiki docs so others don't run in to the same issues.

Also wrote tests together and verified in the UI that the changes are working as expected.

**Comment by asalant** [comment]
FYI - it has been a while since deploying changes and it looks like some of the plumbing in the pipeline - notably CircleCI - is running into errors. I will investigate soon but this is blocking deploying these changes.

**Pull request merged**
