### PR TITLE
Responsive layout

### PR DESCRIPTION
**Pull request by asalant**
Freehub was originally created before smartphone web browsers and has not been updated to be mobile-friendly. Until now.

This PR adds styling to make the Freehub two column layout collapse to one column on narrow screens. It uses flexbox to accomplish this. 

This PR also adds explicit styling to form elements so they look and behave consistently across desktop and mobile browsers. 

These changes have been testing in:
* Chrome on OS X
* Chrome emulator for various iOS and Android browsers
* Chrome on iPhone 8
* Safari on iPhone 8

Many thanks to @jgravois for kicking off this effort and for helping to bring it across the finish line.

### CODE REVIEW

**Comment by asalant** [comment]
Wow. css-grid is nuts. I'm realizing how much I don't understand ;-) I'll need to read a bit to think about how to set it up best for Freehub overall. @jgravois I'd love to hear your thoughts if you have suggestions.

**Comment by jgravois** [comment]
I only know enough to be dangerous.

to be clear, in my own mockup only the application content is laid out using css-grid. the nav and footer use flexbox instead (which excels at organizing 2 dimensional content).

it should tell you something that the two sites below are how I got familiar with any of it.

* https://codepip.com/games/grid-garden/
* https://flexboxfroggy.com

**Comment by asalant** [comment]
I just realized I have some other tasks to complete on the infrastructure side of things so I probably won't touch this for a couple days. If you want to continue the work you've been doing from this branch, that would be awesome.

**Comment by jgravois** [comment]
> Then I'm thinking I will rework the header so that the nav tabs wrap underneath the application header at narrow widths.

is this what you had in mind?

Screen Shot 2019-12-12 at 8 54 10 AM

if so, I'll start working on porting the changes [here](https://johngravois.com/freehub-css/bikebbq/index.html) in another PR to this branch.

**Comment by jgravois** [comment]
in order to keep the diffs as digestible as possible I've opened a PR for the responsive header using my footer branch as the base here: https://github.com/jgravois/freehub/pull/1

**Comment by asalant** [comment]
@jgravois I just pulled your responsive header into this branch. 

I made one change to add margin to the left side of the tabs:

Screen Shot 2019-12-19 at 2 55 20 PM

**Comment by jgravois** [comment]
> Then this is the screen order I want to tackle:
> * Visits for a day - the main patron sign in screen
 > * Person show - what you see when you find a person
> * Person new - what you see when you add a person
> Sign up
> Reports
> Settings

I'll plan on opening PRs for the pages above one at a time (and in order) unless I hear otherwise.

it's exciting to be making progress after all this time!

**Comment by asalant** [comment]
Regarding our grid layout, I wonder if we should use flex box for the main application contents too. It seems like we have a couple scenarios for application screens to address:

* Two columns that should collapse to one column on narrow screens (e.g. person view, reports index)
* Single column that spans two columns that should use the full screen width on all screens (e.g. person edit, settings)
*  Mixed two column and single column (than spans two columns on wide screens) that should collapse to a single column on narrow screens (e.g. visits sign in page)

It seems that flex box should handle these scenarios well. What do you think?

**Comment by jgravois** [comment]
> It seems that flexbox should handle these scenarios well. What do you think?

the only one that will require a little trickery is the last one, I'll take a stab at doing it that way and see if I can get it to work.

**Comment by asalant** [comment]
@jgravois Building off the flexbox demo I shared with you is working well. I'm just about through all the views. Just a few reports left. You can see what I've done so far in this branch.

**Comment by jgravois** [comment]
wow. I go AFKB for a couple days and you:
* figure out a simpler solution
* plow through the bulk of the views

yeoman's work! 🥇


I pulled down this branch and ran it locally and all the pages I hit looked great in a small width window. besides doing some more QA/QC in different browsers, is there anything left here that I can help with to help you land this PR?

**Comment by asalant** [comment]
:grinning: Once I had the layout figured out the views went fast.

I have a couple more report views to do and then I'll bring in your PRs. Thanks so much for the testing and fixes!

**Comment by asalant** [comment]
One thing I haven't done yet is test on an actual phone. I wouldn't be surprised if some of the form element interactions needed some love. I have an iPhone 8 that I'll test on. If you can also that would be awesome.

**Comment by jgravois** [comment]
I forgot to chime back in but I did some testing with my old Pixel XL and the site looked great!

the submit button dimensions are a bit small, but they're passable.

**Comment by asalant** [comment]
It's live!

Are you regularly in a shop that uses Freehub? I'll stop by the SF Bike
Kitchen in the next week to see if anyone has noticed the changes and has
feedback. If you can do the same that would be awesome.

**Comment by jgravois** [comment]
> Are you regularly in a shop that uses Freehub?

yup. in our shop we log folks in 4 days a week. I'll start collecting feedback and let you know how we get on with it.

thanks so much for collaborating with me on this one. its a godsend!

**Comment by asalant** [comment]
Great. The one observation I had using on my phone is that all of the interactive elements seem really small. They are usable though and I did tweak a couple things where it was extreme.

If use ends up being high on mobile I expect it would be worth revisiting. I have GA set up so can see device stats. For the past year they have been:

Screen Shot 2020-01-15 at 4 52 00 PM

But that is with people trying to use the full width version on their tiny screens. I expect mobile usage will go up with these changes once people discover them.

**Comment by jgravois** [comment]
that's more than I was expecting!

if you want to collect individual bits of feedback in issues over the next couple weeks, I'm happy to help you try and pick them off in individual PRs.

**Pull request merged**
